# Generated by Django 4.0.2 on 2022-02-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostmodel',
            old_name='tag',
            new_name='tags',
        ),
    ]
