# Generated by Django 4.0.2 on 2022-03-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmodel_real_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='shop.ColorModel', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='shop.SizeModel', verbose_name='size'),
        ),
    ]
